run:
  timeout: 5m
linters:
  enable-all: true
  disable:
    - cyclop
    - wsl
    - godox
    - gochecknoglobals
    - ireturn
    - nlreturn
    - testpackage
    - paralleltest
    - exhaustruct
    - gocognit
    - gochecknoinits
    - gocyclo
    - funlen
    - maintidx
    - musttag
    - err113
    - testifylint
    - fatcontext
    - gomoddirectives
linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - "github.com/gatewayd-io"
          - "github.com/getsentry/sentry-go"
          - "github.com/rs/zerolog"
          - "github.com/grpc-ecosystem/grpc-gateway"
          - "google.golang.org/grpc"
          - "google.golang.org/protobuf"
          - "github.com/knadh/koanf"
          - "github.com/panjf2000/gnet/v2"
          - "github.com/spf13/cobra"
          - "github.com/spf13/cast"
          - "github.com/invopop/jsonschema"
          - "github.com/santhosh-tekuri/jsonschema/v5"
          - "github.com/NYTimes/gziphandler"
          - "github.com/go-co-op/gocron"
          - "github.com/prometheus/client_golang/prometheus"
          - "github.com/prometheus/client_model/go"
          - "github.com/prometheus/common/expfmt"
          - "github.com/hashicorp/go-hclog"
          - "github.com/Masterminds/semver/v3"
          - "github.com/hashicorp/go-plugin"
          - "github.com/mitchellh/mapstructure"
          - "github.com/google/go-cmp"
          - "github.com/google/go-github/v53/github"
          - "github.com/codingsince1985/checksum"
          - "golang.org/x/exp/maps"
          - "golang.org/x/exp/slices"
          - "gopkg.in/yaml.v3"
          - "github.com/zenizh/go-capturer"
          - "gopkg.in/natefinch/lumberjack.v2"
          - "github.com/expr-lang/expr"
          - "github.com/jackc/pgx/v5/pgproto3"
          - "github.com/cybercyst/go-scaffold/pkg/scaffold"
          - "golang.org/x/text/cases"
          - "golang.org/x/text/language"
          - "github.com/redis/go-redis/v9"
          - "github.com/spaolacci/murmur3"
          - "github.com/testcontainers/testcontainers-go"
          - "github.com/stretchr/testify/require"
          - "github.com/docker/go-connections/nat"
      test:
        files:
          - $test
        allow:
          - $gostd
          - "github.com/gatewayd-io"
          - "github.com/stretchr/testify"
          - "github.com/rs/zerolog"
          - "github.com/zenizh/go-capturer"
          - "github.com/hashicorp/go-hclog"
          - "github.com/prometheus/client_golang/prometheus"
          - "github.com/prometheus/client_model/go"
          - "github.com/prometheus/common/expfmt"
          - "github.com/panjf2000/gnet/v2"
          - "github.com/spf13/cobra"
          - "github.com/knadh/koanf"
          - "github.com/spf13/cast"
          - "github.com/jackc/pgx/v5/pgproto3"
          - "github.com/testcontainers/testcontainers-go"
          - "github.com/redis/go-redis/v9"
          - "github.com/docker/go-connections/nat"
  tagalign:
    align: false
    sort: false
    order:
      - json
      - jsonschema
