global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "gatewayd-aggregated-metrics"
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ["gatewayd:9090"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]
